# Generated by Django 4.2.1 on 2023-11-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='seo_title')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='seo_description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='seo_keywords')),
                ('og_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='seo og:title')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo', verbose_name='seo og:image')),
                ('og_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='seo og:description')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
